import React from 'react'
import { Metadata } from 'next';


export const metadata: Metadata = {
    title: "Layout Admin BautiDev",
    description: "Generated by create next app",
  };


export default function Layout(children: React.ReactNode) {
  return (
    <div>{children}</div>
  )
}
