import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Layout Auth BautiDev",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="grid grid-cols-1 h-screen md:grid-cols-2">
      <div className="flex flex-col items-center justify-center">{children}</div>
      <div className="bg-[url('/bg-login.png')] bg-no-repeat bg-cover h-full w-full hidden md:block"></div>
    </div>
  );
}
